OutfitGenerator/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Outfits.urls'))
]

Outfits/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [
    # path('',views.HomePageView.as_view(),name='home'),
    path('login/',auth_views.LoginView.as_view(redirect_authenticated_user=True),name='login'),
    #path('meh',views.CheckUserView,name='checkuser'),
    path('signup/',views.signup,name='signup'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('dashboard/',views.dashboardView,name='dashboard'),
    path('newitem/',views.add_clothes,name='newitem'),
    path('myclothes/',views.view_clothes,name='myclothes'),
    path('chatai/',views.chat_ai,name='chatai'),
    path('imageai/',views.image_ai),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Outfits/models.py
from typing import Any

from django.db import models

from django.contrib.auth.models import User

from django.urls import reverse

from . import generate

from . import storage

from PIL import Image

import os

from django.http import JsonResponse

 

# os.path.relpath("C:\\Users\\uyiosa.igbinedion\\OneDrive - Interswitch Limited\Documents\\OutfitGenerator\\media\\outfitgenerator pics")

 

# Create your models here.

class ClothingItem(models.Model):

    # user =   models.CharField(max_length = 20) #models.ForeignKey(User,on_delete=models.CASCADE)

    category = models.CharField(max_length = 100)

    name = models.CharField(max_length = 50)

    image = models.ImageField(default = 'default.jpg',upload_to='clothes_pics')

    user = 'ali'

 

    def __str__(self):

        return "{}'s {}".format(self.user,self.name)

   

    def get_absolute_url(self):

        return reverse('dashboard',args=[0])

   

    def save(self,*args, **kwargs):

        super().save(*args, **kwargs)

 

        #Create Product

        # project_id = "primeval-creek-394208"
        project_id = "primeval-creek-394208"

        location =  "europe-west1"

        product_id = self.user + "_" + str(self.id) + 'new'

        product_set_id = self.user + "_PS"

        product_display_name = self.name

        product_category = "apparel"

        key = "category"

        value = self.category

        generate.create_product(project_id,location,product_id,product_display_name,product_category)

 

        #Add Product to Product Set

        generate.add_product_to_product_set(project_id,location,product_id,product_set_id)

 

        #Add product labels

        generate.update_product_labels(project_id,location,product_id,key,value)

 

        #Upload image to storage

        path = self.image.path

        bucket = "vortex-new-bucket"

        file_name = self.name.replace(" ","") + str(self.id)

        storage.upload_blob(bucket,path,file_name)

 

        #Create Reference Image

        ref_id = "REFIMAGE-" + str(self.id)

        uri = "gs://vortex-new-bucket/" + file_name

        generate.create_reference_image(project_id,location,product_id,ref_id,uri)

        # img = Image.open(self.image)

 

        # if img.height > 300 or img.width > 300:

        #     output_size = (300,300)

        #     img.thumbnail(output_size)

        #     img.save(self.image)

 

        # if 'work'in event:

        #     StyleOne.objects.create(season ='winter')

        #     p1 = PossibleItem.objects.create(category=self.category,name=self.name,image='clothes_pics/'+ os.path.basename(self.image.path) )

        #     StyleOne.objects.last().items.add(p1)

 

        # elif 'casual' in event:

        #     StyleTwo.objects.create(season ='winter')

        #     p1 = PossibleItem.objects.create(category=self.category,name=self.name,image='clothes_pics/'+ os.path.basename(self.image.path) )

        #     StyleOne.objects.last().items.add(p1)

 

        # elif 'casual' in event:

        #     StyleThree.objects.create(season ='winter')

        #     p1 = PossibleItem.objects.create(category=self.category,name=self.name,image='clothes_pics/'+ os.path.basename(self.image.path) )

        #     StyleOne.objects.last().items.add(p1)

       

       

       

       

   

 

class BadOutfit(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    items = models.ManyToManyField(ClothingItem)

 

    def __str__(self):

        return "Outfit:{}, Disliked by {}".format(self.id,self.user)

 

 

class PossibleItem(models.Model):

    category = models.CharField(max_length = 100,default='upper')

    name = models.CharField(max_length = 100,default='shirt')

    image = models.ImageField(default='default.jpg',upload_to='clothes_pics')

 

    def __str__(self):

        return "{}".format(self.name)

   

    # def save(self):

    #     super().save()

    #     img = Image.open(self.image.path)

       

    #     if img.height > 300 or img.width > 300:

    #         output_size = (300,300)

    #         img.thumbnail(output_size)

    #         img.save(self.image.path)

 

 

class StyleOne(models.Model):

    #Alex Costa Youtube Channel

    season = models.CharField(max_length = 100)

    items = models.ManyToManyField(PossibleItem)

    category = models.CharField(max_length = 100)

    name = models.CharField(max_length = 50)

    image = models.ImageField(default = 'default.jpg',upload_to='clothes_pics')

   

    def __str__(self):

        return "Alex Costa outfit #{}".format(self.id)

 

class StyleTwo(models.Model):

    #AlphaM Youtube Channel

    season = models.CharField(max_length = 100)

    items = models.ManyToManyField(PossibleItem)

    category = models.CharField(max_length = 100)

    name = models.CharField(max_length = 50)

    image = models.ImageField(default = 'default.jpg',upload_to='clothes_pics')

   

    def __str__(self):

        return "AlphaM outfit #{}".format(self.id)

 

class StyleThree(models.Model):

    #TMF Youtube Channel

    season = models.CharField(max_length = 100)

    items = models.ManyToManyField(PossibleItem)

    category = models.CharField(max_length = 100)

    name = models.CharField(max_length = 50)

    image = models.ImageField(default = 'default.jpg',upload_to='clothes_pics')

   

    def __str__(self):

        return "TMF outfit #{}".format(self.id)

templates/chatai.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Outfit Generator</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->


    <!-- Header -->
    <header class="masthead">
      <div class="container d-flex h-100 align-items-center">
        <div class="mx-auto text-center">
          <h1 class="mx-auto my-0 text-uppercase" >Outfit Generator</h1>
          <h2 style = "color:white !important;" class="text-white-50 mx-auto mt-2 mb-5">Making picking outfits easy.</h2>
          {% if request.user.is_authenticated %}
          <a href="{% url 'dashboard' 0%}" class="btn btn-primary js-scroll-trigger">View Dashboard</a>
          <a href="{% url 'logout' %}" class="btn btn-primary js-scroll-trigger">Logout</a>
          {% else %} 
          <a href="{% url 'login'%}" class="btn btn-primary js-scroll-trigger">Login</a>
          <a href = "{% url 'signup'%}"class="btn btn-primary js-scroll-trigger">Create Account</a>
          {% endif %}
        </div>
      </div>
    </header>

    <!-- Bootstrap core JavaScript -->

    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->

    <!-- Custom scripts for this template -->

  </body>

</html>

templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->

    <!-- Page Header -->
    <header class="masthead text-center text-white">
      <div class="masthead-content">
        <div class="container">
          <h1 class="masthead-heading mb-0">Hello {{user.username}}</h1>
        </div>
      </div>
    </header>


    <!-- Post Content -->
    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 order-lg-2">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'img/addclothes.jpg'%}" alt="">
            </div>
          </div>
          <div class="col-lg-6 order-lg-1">
            <div class="p-5">
              <center><a class = "btn btn-outline-primary" href="{% url 'newitem' %}"><h2 class="linkBtns">Add Clothes</h2></a></center>
              <p>Add all your current clothing items, and we'll use them to create amazing outfits!</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    
  {% if not styleChosen %}
  <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'img/choosestyle.jpg'%}" alt="">
            </div>
          </div>
          <div class="col-lg-6">
            <div class="p-5">
              <center><a class = "btn btn-outline-primary" id = "choiceBtn" href="#"><h2 class="linkBtns">Choose a style preference.</h2></a></center>
              <p>What do you want to look like? We'll use your clothing items to generate outfits similar to your style preferences.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    {% endif %}
    <!-- Main Content -->
  
    {% if styleChosen %}
    <section>
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6">
              <div class="p-5">
                <img class="img-fluid rounded-circle" src="{% static 'img/choosestyle.jpg'%}" alt="">
              </div>
            </div>
            <div class="col-lg-6">
              <div class="p-5">
                <center><a class = "btn btn-outline-primary" id = "choiceBtn" href="#"><h2 class="linkBtns">Change Style</h2></a></center>
                <p>What do you want to look like? We'll use your clothing items to generate outfits similar to your style preferences.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    {% endif %}

    <section>
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
              <div class="p-5">
                <img class="img-fluid rounded-circle" src="{% static 'css/generate.jpg'%}" alt="">
              </div>
            </div>
            <div class="col-lg-6 order-lg-1">
              <div class="p-5">
                <center><a class = "btn btn-outline-primary" id = "myBtn" href="#"><h2 class="linkBtns">Generate Outfit</h2></a></center>
                <p>We will pick your next oufit, to prevent you from having to think about it, while still looking great!</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    
      <section>
        <div class="container">
          <div class="row align-items-center">
            <div class="col-lg-6">
              <div class="p-5">
                <img class="img-fluid rounded-circle" src="{% static 'img/bg-masthead.jpg' %}" alt="">
              </div>
            </div>
            <div class="col-lg-6">
              <div class="p-5">
                  <center><a class = "btn btn-outline-primary" href="{% url 'myclothes' %}"><h2 class="linkBtns">View my clothes</h2></a></center>
                <p>Have a look to see if you've added all your clothes.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

<!-- -Possibly Needed -->
    <!-- <div class="clearfix">
        <a href="{% url 'myclothes' %}"><h2 class="display-4">View my clothes</h2></a>
    </div>

    {% if not styleChosen %}
      <h4> You have not chosen a style preference</h4>
      <h4> Outfits are generated at random if you do not choose one </h4>
      <div class="clearfix">
          <center><a class="btn btn-primary" id = "choiceBtn" href="#">Choose Style Preference</a></center>
      </div>
    {% else %}
    <div class="clearfix">
        <center><a class="btn btn-primary" id = "choiceBtn" href="#">Change Style Preference</a></center>
    </div>
    {% endif %}


    <div class="clearfix">
        <center><a id = "myBtn" href="#"><h2 class="display-4">Generate Outfit</h2></a></center>
    </div> -->
<!-- > -->
<!--Modals-->
    <div id = "myModal" class = "modal">
      <div class = "modal-content">
        
        {% if not styleChosen %}
        <center><h4>No Style Preference Selected!</h4></center>
        <a href = "{% url 'dashboard' 0%}"><span class = "close">&times;</span></a>
        <div class="clearfix">
          <center><a class="btn btn-primary" id = "choiceBtn" href="#">Choose Style Preference</a></center>
        </div>  
        {% elif insufficient %}
          <center><h4>Could not generate outfit due to lack of clothes!</h4></center>
          <a href = "{% url 'dashboard' 0%}"><span class = "close">&times;</span></a>
          <div class="clearfix">
            <center><a class="btn btn-primary" href="{% url 'newitem' %}">Click here to add Clothes</a></center>
          </div>
        {% else %}
        <span class = "close">&times;</span>
        <center><h2>Your Outfit!</h2></center>
        {% for cloth in myclothes.values %}
<!-- Name<h3 id="name">{{cloth.0.name}}</h3>EndName -->
<!--Image--><img src = "{{MEDIA_URL}}{{cloth.0.image}}"><!--EndImage-->
      {% endfor %}
      <div class="clearfix">
        <center><a class="btn btn-primary" id = "newBtn" href="#">Generate another</a></center>
      </div>

      <div class="clearfix">
          <form action="" method="POST">
              {% csrf_token %}
              <center><input class = "btn btn-primary" type="submit" name="Dislike" value="Dislike" /></center>
          </form>
      </div>
        {% endif %}


      </div>
    </div>

    <div id = "myModal1" class = "modal">
      <div class = "modal-content">
        <a href = "{% url 'dashboard' 0%}"><span id = "closeChoice">&times;</span></a>
        <div class="clearfix">
          <form id = "choiceForm" action = "" method = "POST">
            {% csrf_token %}
            <div class="row">
              <div class="column">
                <!-- <center><img src="{% static 'img/alexcosta.jpg' %}" alt="" style="width:90%; height: 300px"></center> -->
                <center><a class="btn btn-primary" id = "Style1" href="{% url 'dashboard' 1%}">Corporate Fit</a></center>
              </div>
              <div class="column">
                <!-- <center><img src="{% static 'img/alpham.jpg' %}" alt="Forest" style="width:90%; height: 300px"></center> -->
                <center><a class="btn btn-primary" id = "Style2" href="{% url 'dashboard' 2%}">Business Fit</a></center>
              </div>
              <div class="column">
                <!-- <center><img src="{% static 'img/TMF.jpg' %}" alt="Mountains" style="width:90%; height: 300px"></center> -->
                <center><a class="btn btn-primary" id = "Style3" href="{% url 'dashboard' 3%}">Casual Fit</a></center>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
    
    <div id = "loadingModal" class = "modal">
      <div class = "modal-content">
        <img src = "{% static 'img/loading.jpg' %}">
      </div>
    </div>




    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">Copyright &copy; Outfit Generator</p>
            <h5 id = "num">{{style}}</h5>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Custom scripts for this template -->
    <script>
      // Get the modal
        var currStyle = document.getElementById("num")
        var modal = document.getElementById("myModal");
        var choiceModal = document.getElementById("myModal1")
        var loadingModal = document.getElementById("loadingModal")

        // Get the button that opens the modal
        var styleOne = document.getElementById("Style1")
        var styleTwo = document.getElementById("Style2")
        var styleThree = document.getElementById("Style3")
        var btn = document.getElementById("myBtn");
        var newBtn = document.getElementById("newBtn");
        var choiceBtn = document.getElementById("choiceBtn")

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];
        var closeChoice = document.getElementById("closeChoice")

        currStyle.style.display = "none";

        // When the user clicks the button, open the modal 
        var clicked = false
        styleOne.onclick = function(){
          choiceModal.style.display = "none";
          loadingModal.style.display = "block";
        }
        styleTwo.onclick = function(){
          choiceModal.style.display = "none";
          loadingModal.style.display = "block";
        }
        styleThree.onclick = function(){
          choiceModal.style.display = "none";
          loadingModal.style.display = "block";
        }
        btn.onclick = function() {
          //alert('http://127.0.0.1:8000/dashboard/' + currStyle.innerHTML)
          //alert("hey you clicked me")
          modal.style.display = "block";
        }

        choiceBtn.onclick = function(){
          //alert("hey you clicked me")
          choiceModal.style.display = "block";
        }

        newBtn.onclick = function(){
          modal.style.display = "none";
          loadingModal.style.display = "block";
          var url = 'http://127.0.0.1:8000/dashboard/' + currStyle.innerHTML
          $.ajax({
            method:"GET",
            url: url,
            success:function(data){
              //First Name indices
              loadingModal.style.display = "none";
              modal.style.display = "block";
              // Stored all names in array
              itemNames = []
              //Store all images in Array
              itemImages = []
              //console.log(firstNewImage)
              //console.log(secondNewImage)
                //Change name and images of all items
              lines = data.split('\n')
              for (i=0;i<lines.length;i++){
                if (lines[i].startsWith('<!--Name')){
                  startingIndex = lines[i].indexOf('<h3')+14
                  endingIndex = lines[i].indexOf('</h3>')
                  itemNames.push(lines[i].slice(startingIndex,endingIndex))
                } else if(lines[i].startsWith('<!--Image')){
                  startingImageIndex = lines[i].indexOf('<img')
                  endingImageIndex = lines[i].indexOf('<!--End')
                  itemImages.push(lines[i].slice(startingImageIndex,endingImageIndex))
                }
              
              }
              for (i=0;i<itemNames.length;i++){
                  document.getElementsByTagName('h3')[i].innerHTML = itemNames[i]
                  document.getElementsByTagName('img')[i].outerHTML = itemImages[i]
              }
              console.log(itemImages)
            },
            failure: function(data){
              console.log('fail bro')
            }
          })
          //modal.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
          //alert("hey you clicked me")
          modal.style.display = "none";

        }

        closeChoice.onclick = function(){
          alert("hey")
          choiceModal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
          if (event.target == choiceModal){
            choiceModal.style.display = "none";
          }
        }
    </script>
  </body>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DressAI</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->


    <!-- Header -->
    <header class="masthead">
      <div class="container d-flex h-100 align-items-center">
        <div class="mx-auto text-center">
          <h1 class="mx-auto my-0 text-uppercase" >DressAI</h1>
          <h2 style = "color:white !important;" class="text-white-50 mx-auto mt-2 mb-5">Making picking outfits easy.</h2>
          {% if request.user.is_authenticated %}
          <a href="{% url 'dashboard' 0%}" class="btn btn-primary js-scroll-trigger">View Dashboard</a>
          <a href="{% url 'logout' %}" class="btn btn-primary js-scroll-trigger">Logout</a>
          {% else %} 
          <a href="{% url 'login'%}" class="btn btn-primary js-scroll-trigger">Login</a>
          <a href = "{% url 'signup'%}"class="btn btn-primary js-scroll-trigger">Create Account</a>
          {% endif %}
        </div>
      </div>
    </header>

    <!-- Bootstrap core JavaScript -->

    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->

    <!-- Custom scripts for this template -->

  </body>

</html>

templates/myclothes.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>Your Clothes</title>
	<meta charset="UTF-8">
	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"/>
	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/viewclothes.css' %}"/>
</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>


	<!-- Header section -->
	<header class="header-section">
		<div class="container">
            <nav>
                <ul>
                    <li><a href="#" class="site-logo">
                       <h2 style = "color:white;"></h2>
                        </a>
                    </li>
                </ul>
            </nav>
		</div>
	</header>	
	
	<!-- Shop section  -->
	<section class="shop-section">
        <center><h1>Your Clothes</h1></center>
		<div class="container">
			<div class="row">
                {% for cloth in clothes %}
                    {% if cloth.user == user%}
                        <div class="col-lg-3 col-sm-6">
                            <div class="shop-item">
                                <img src="{{MEDIA_URL}}{{cloth.image}}" alt="">
                                <h3>{{cloth.name}}</h3>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
			</div>
		</div>
	</section>
	<!-- Shop section end -->
	



	<!-- Footer section -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <p class="copyright text-muted">Copyright &copy; Outfit Generator</p>
          </div>
        </div>
      </div>
    </footer>
	       

	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'js/viewclothes.js' %}"></script>

	</body>
</html>

templates/newitem.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->

    <!-- Page Header -->
    <header class="masthead" style="background-color: #232323">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1 style = "color: white !important">Add Item</h1>
            </div>
          </div>
        </div>
      </div>
    </header>
    
    <!-- Navigation -->


    <!-- Form -->
    <form action = "" method = "POST" enctype="multipart/form-data">
      {% csrf_token %}
    
      <div class = "form-group">
      <tr><th><label for="id_user">User:</label></th><td><select class = "form-control" name="user" required id="id_user">
          <option value={{request.user.id}} selected>{{request.user}}</option>
        
        </select></td></tr>
      <br>
      <br>
        <tr><th><label for="id_category">Category:</label></th><td><input class = "form-control" type="text" name="category" maxlength="20" required id="id_category"></td></tr> 
        
        <br>
      <br>
        <tr><th><label for="id_name">Name:</label></th><td><input class = "form-control" type="text" name="name" maxlength="20" required id="id_name"></td></tr>
      <br>
      <br>
        <tr><th><label for="id_image">Image:</label></th><td><input class = "form-control-file" type="file" name="image" accept="image/*" id="id_image"></td></tr>
      <br>
      <br>
      <center><input class = "btn btn-primary" type = "submit" value = "Add Item to List"></center>
      </div>
    </form>
    <!-- Bootstrap core JavaScript -->

    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->

    <!-- Custom scripts for this template -->

  </body>

</html>



  
  